### PR TITLE
FKVR-74: Desktop interaction refinements, and more!

### PR DESCRIPTION
**Pull request by patrickocoffeyo**
# [FKVR-74](https://fourkitchens.atlassian.net/browse/FKVR-74)
**This PR introduces the following changes:**
- Makes modal hotspots _actually_ clickable with the mouse raycaster.
- Removes the fuse cursor from the desktop experience.
- Allows desktop users to close modals by clicking away from the modal.
- Adds support for the Daydream, Vive, and Oculus Rift controllers. (Only tested with Daydream, me no haz Vive or Rift yet).
- Improves consistency of modal interactions (Solves a rare bug that caused modals to sometimes open randomly).

## Steps to Test
- [x] Checkout this branch.
- [x] Run `yarn i` in this repo's root.
- [x] Run `yarn start` in this repo's root.
- [x] Open the app in your desktop browser.
- [x] Ensure you can open and close modals with hotspots/close button, and by clicking anywhere on the sky.
- [x] Ensure opening a modal closes other open modals.
- [ ] Open the app in Android Chrome over your local network.
- [ ] Note that you see a fuse cursor, and can use it to close/open modals via the hotspots.
- [ ] Enter VR mode.
- [ ] Insert your phone into the Daydream headset, initialize your controller, and ensure your Daydream controller loads into the scene. This might take a second, and also might require you to perform one click after initializing the controller, as the gamepad API is sometimes slow to call the event handlers that cause the controller to show up, and the fuse cursor to disappear.
- [ ] Note that you can activate hotspots by pointing to them and clicking on them with your Daydream controller.

## Note
I need to test the Cardboard (fuse-based interactions) with this update. I'm charging my iPad so I can do this in Safari, as Chrome for Android now integrates very tightly with Daydream, and won't let you load a WebVR app in Cardboard (even with NFC off). I need to look into this and figure it out, that's the only outstanding part of this ticket.

### CODE REVIEW

**Comment by infiniteluke** [comment]
I don't have my Android phone with me ATM but things are looking good up to that point. 

I noticed that when a modal is open, clicking anywhere in the scene closes it, not just the `X` or another modal. Is that desired?

**Comment by patrickocoffeyo** [comment]
@infiniteluke Thanks for taking a look! In regards to modals and clicks, the mouse-cursor raycaster component we're using is kind of janky, and it doesn't fire specific click events for some objects. I looked through the component's code and it's kind of a mess, AKA hard to debug, so I suspect sometime in the near future we'll need to build our own. The click listener added in this PR is kind of a kludge around other shortcomings of that component, so I'm hoping to get time to write our own soon.

**Comment by fkbender** [comment]
This works really well on Desktop! Let's merge it!!

**Comment by fkbender** [comment]
apparently I'm logged in as bender. beep beep boop boop, guzzle beer and be destructive!!!!

**Comment by patrickocoffeyo** [comment]
Roger that @fkbender, boop beep, shipping now!

**Pull request merged**
